### ISSUE TITLE
(lambda x: x+3) % Just(2)

### ISSUE THREAD

**Issue by PlumpHip** [dbrattli/OSlash#27]
>>> (lambda x: x+3) % Just(2)

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unsupported operand type(s) for %: 'function' and 'Just'
>>>

Thanks

**Comment by PlumpHip** [comment]
>>> from oslash import *
>>> List([lambda x: x*2, lambda y: y+3]) * List([1, 2, 3])

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "python3-3.8.3/lib/python3.8/typing.py", line 875, in __new__
    obj = super().__new__(cls, *args, **kwds)
TypeError: object.__new__() takes exactly one argument (the type to instantiate)
